"""esquema inicial

Revision ID: 22d28227017e
Revises: 
Create Date: 2026-08-07 00:32:48.216794
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.core.crypto  # tipo TextoCifrado (AES-256-GCM a nivel de columna)

revision: str = '22d28227017e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumo_cuota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuente', sa.Enum('football-data', 'api-football', name='fuente', native_enum=False, length=20), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('errores', sa.Integer(), nullable=False),
    sa.Column('ultimo_request', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuente', 'dia', name='uq_cuota_fuente_dia')
    )
    with op.batch_alter_table('consumo_cuota', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumo_cuota_dia'), ['dia'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumo_cuota_fuente'), ['fuente'], unique=False)

    op.create_table('ejecuciones_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=60), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exito', sa.Boolean(), nullable=False),
    sa.Column('registros_afectados', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ejecuciones_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ejecuciones_job_job'), ['job'], unique=False)

    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('nombre_corto', sa.String(length=60), nullable=True),
    sa.Column('liga', sa.String(length=80), nullable=False),
    sa.Column('pais', sa.String(length=80), nullable=False),
    sa.Column('escudo_url', sa.String(length=300), nullable=True),
    sa.Column('fuente', sa.Enum('football-data', 'api-football', name='fuente', native_enum=False, length=20), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuente', 'external_id', name='uq_equipo_fuente_external')
    )
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipos_liga'), ['liga'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipos_nombre'), ['nombre'], unique=False)

    op.create_table('metricas_jornada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liga', sa.String(length=80), nullable=False),
    sa.Column('temporada', sa.String(length=20), nullable=True),
    sa.Column('jornada', sa.Integer(), nullable=True),
    sa.Column('modelo_version', sa.String(length=40), nullable=False),
    sa.Column('partidos_evaluados', sa.Integer(), nullable=False),
    sa.Column('aciertos', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('brier', sa.Float(), nullable=True),
    sa.Column('calculado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liga', 'temporada', 'jornada', 'modelo_version', name='uq_metrica_j')
    )
    with op.batch_alter_table('metricas_jornada', schema=None) as batch_op:
        batch_op.create_index('ix_metrica_liga_temporada', ['liga', 'temporada'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', app.core.crypto.TextoCifrado(length=512), nullable=False),
    sa.Column('email_indice', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('usuario', 'admin', name='rol', native_enum=False, length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('totp_secreto', app.core.crypto.TextoCifrado(length=512), nullable=True),
    sa.Column('totp_activo', sa.Boolean(), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email_indice'), ['email_indice'], unique=True)

    op.create_table('versiones_modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('algoritmo', sa.String(length=60), nullable=False),
    sa.Column('entrenado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('partidos_entrenamiento', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('log_loss', sa.Float(), nullable=True),
    sa.Column('brier', sa.Float(), nullable=True),
    sa.Column('metricas_detalle', sa.JSON(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('versiones_modelo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_versiones_modelo_version'), ['version'], unique=True)

    op.create_table('logs_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('exito', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detalle', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs_acceso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_acceso_accion'), ['accion'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_acceso_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_acceso_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_local_id', sa.Integer(), nullable=False),
    sa.Column('equipo_visitante_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('liga', sa.String(length=80), nullable=False),
    sa.Column('temporada', sa.String(length=20), nullable=True),
    sa.Column('jornada', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('programado', 'en_juego', 'finalizado', 'suspendido', name='estadopartido', native_enum=False, length=20), nullable=False),
    sa.Column('goles_local', sa.Integer(), nullable=True),
    sa.Column('goles_visitante', sa.Integer(), nullable=True),
    sa.Column('resultado_real', sa.Enum('L', 'E', 'V', name='resultado', native_enum=False, length=2), nullable=True),
    sa.Column('fuente', sa.Enum('football-data', 'api-football', name='fuente', native_enum=False, length=20), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['equipo_local_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['equipo_visitante_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuente', 'external_id', name='uq_partido_fuente_external')
    )
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.create_index('ix_partido_fecha_liga', ['fecha', 'liga'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidos_equipo_local_id'), ['equipo_local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidos_equipo_visitante_id'), ['equipo_visitante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidos_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidos_liga'), ['liga'], unique=False)

    op.create_table('ratings_elo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('partidos_jugados', sa.Integer(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ratings_elo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_elo_equipo_id'), ['equipo_id'], unique=True)

    op.create_table('sesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocada', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sesiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesiones_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_sesiones_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('features_partido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('forma_reciente_local', sa.Float(), nullable=False),
    sa.Column('forma_reciente_visitante', sa.Float(), nullable=False),
    sa.Column('h2h_local_wins', sa.Integer(), nullable=False),
    sa.Column('h2h_draws', sa.Integer(), nullable=False),
    sa.Column('h2h_away_wins', sa.Integer(), nullable=False),
    sa.Column('dias_descanso_local', sa.Float(), nullable=False),
    sa.Column('dias_descanso_visitante', sa.Float(), nullable=False),
    sa.Column('goles_favor_local', sa.Float(), nullable=False),
    sa.Column('goles_contra_local', sa.Float(), nullable=False),
    sa.Column('goles_favor_visitante', sa.Float(), nullable=False),
    sa.Column('goles_contra_visitante', sa.Float(), nullable=False),
    sa.Column('elo_local', sa.Float(), nullable=False),
    sa.Column('elo_visitante', sa.Float(), nullable=False),
    sa.Column('calculado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features_partido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_partido_partido_id'), ['partido_id'], unique=True)

    op.create_table('predicciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('prob_local', sa.Float(), nullable=False),
    sa.Column('prob_empate', sa.Float(), nullable=False),
    sa.Column('prob_visitante', sa.Float(), nullable=False),
    sa.Column('marcador_probable_local', sa.Integer(), nullable=True),
    sa.Column('marcador_probable_visitante', sa.Integer(), nullable=True),
    sa.Column('modelo_version', sa.String(length=40), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partido_id', 'modelo_version', name='uq_prediccion_partido_version')
    )
    with op.batch_alter_table('predicciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predicciones_modelo_version'), ['modelo_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_predicciones_partido_id'), ['partido_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predicciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predicciones_partido_id'))
        batch_op.drop_index(batch_op.f('ix_predicciones_modelo_version'))

    op.drop_table('predicciones')
    with op.batch_alter_table('features_partido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_partido_partido_id'))

    op.drop_table('features_partido')
    with op.batch_alter_table('sesiones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesiones_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_sesiones_token_hash'))

    op.drop_table('sesiones')
    with op.batch_alter_table('ratings_elo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_elo_equipo_id'))

    op.drop_table('ratings_elo')
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partidos_liga'))
        batch_op.drop_index(batch_op.f('ix_partidos_fecha'))
        batch_op.drop_index(batch_op.f('ix_partidos_equipo_visitante_id'))
        batch_op.drop_index(batch_op.f('ix_partidos_equipo_local_id'))
        batch_op.drop_index('ix_partido_fecha_liga')

    op.drop_table('partidos')
    with op.batch_alter_table('logs_acceso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_acceso_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_logs_acceso_timestamp'))
        batch_op.drop_index(batch_op.f('ix_logs_acceso_accion'))

    op.drop_table('logs_acceso')
    with op.batch_alter_table('versiones_modelo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_versiones_modelo_version'))

    op.drop_table('versiones_modelo')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email_indice'))

    op.drop_table('usuarios')
    with op.batch_alter_table('metricas_jornada', schema=None) as batch_op:
        batch_op.drop_index('ix_metrica_liga_temporada')

    op.drop_table('metricas_jornada')
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipos_nombre'))
        batch_op.drop_index(batch_op.f('ix_equipos_liga'))

    op.drop_table('equipos')
    with op.batch_alter_table('ejecuciones_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ejecuciones_job_job'))

    op.drop_table('ejecuciones_job')
    with op.batch_alter_table('consumo_cuota', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumo_cuota_fuente'))
        batch_op.drop_index(batch_op.f('ix_consumo_cuota_dia'))

    op.drop_table('consumo_cuota')
    # ### end Alembic commands ###
